services:
  postgres_local:
    container_name: postgres_db
    build:
      context: .
      dockerfile: ./docker/postgres.dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=test_user
      - POSTGRES_DB=moddingway